---
branches:
  - master
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets:
        - path: "fortigate-exporter.linux.amd64"
          label: "Linux AMD64"
        - path: "fortigate-exporter.windows.amd64.exe"
          label: "Windows AMD64"
        - path: "fortigate-exporter.darwin.amd64"
          label: "Darwin AMD64"
