version: '3'

services:
  prometheus_fortigate_exporter:
    build: ./
    ports:
      - 9710:9710
    volumes:
      - /path/to/fortigate-key.yaml:/config/fortigate-key.yaml
    restart: unless-stopped
