inputs:
  go-version:
    description: 'go version to use'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
